name: time_minder
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.0
  intl: ^0.19.0
  path: ^1.8.3
  sqflite: ^2.3.3+1
  logger: ^2.2.0
  timer_count_down: ^2.2.2
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.0.12
  curved_labeled_navigation_bar: ^2.0.2
  flutter_local_notifications: ^17.0.0
  flutter_dnd: ^0.1.4+1
  audioplayers: ^6.0.0
  audioplayers_web: ^5.0.0
  circular_countdown_timer: ^0.2.3
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.5
  double_back_to_close_app: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.3
  timezone: ^0.9.3
  easy_date_timeline: ^1.0.6
  table_calendar: ^3.1.1
  tutorial_coach_mark: ^1.2.11
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/helps/
    - assets/fonts/
    - assets/sounds/
  fonts:
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans.ttf
